stages:
  - test
  - report
  - notification

web:
  stage: test
  before_script:
    - npm ci
    - npx playwright install --with-deps
  script:
    - npx playwright test --config=playwright.web.config.ts
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"

generate_report:
    stage: report
    script:
      - echo "Generating report..."
    rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_PIPELINE_SOURCE == "schedule"

slack:
    stage: notification
    script:
      - echo "Sending notification to Slack..."
    rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_PIPELINE_SOURCE == "schedule"
