stages:
  - test
  - report
  - notification

web:
    stage: test
    script:
      - echo "Running web tests..."
    rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_PIPELINE_SOURCE == "schedule"

generate_report:
    stage: report
    script:
      - echo "Generating report..."
    rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_PIPELINE_SOURCE == "schedule"

slack:
    stage: notification
    script:
      - echo "Sending notification to Slack..."
    rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_PIPELINE_SOURCE == "schedule"
